### ISSUE TITLE
Example not working

### ISSUE THREAD

**Issue by delaneyj** [a-h/templ-vscode#1]
using `v0.2.194`  had a bunch of issues trying to use and went back to just the initial example.  Getting `expected declaration, found 'package'`.  Yet

```bash
➜  templtest templ generate
example.templ complete in 10.625784ms
Generated code for 1 templates with 0 errors in 11.394882ms
➜  templtest templ fmt
^C
➜  templtest templ fmt ./...
example.templ complete in 6.66653ms
Formatted 1 templat
```

Also if I cut a part of the template, save, undo... parts of the clipboard get save on fmt.  Its really hard to explain but can show in video maybe?  I reach out on the Gopher Slack and curious if you are still pursuing this.  Very interested in using but didn't want to bother you if you've moved on.

VSCode's output/templ says
```go
[Info  - 4:28:32 PM] 2023/02/15 16:28:32 go env for /home/delaney/work/templtest
(root /home/delaney/work/templtest)
(go version go version go1.20.1 linux/amd64)
(valid build configuration = true)
(build flags: [])
GO111MODULE=
GOINSECURE=
GOROOT=/home/delaney/.gvm/gos/go1.20.1
GOPRIVATE=
GOFLAGS=
GONOPROXY=
GONOSUMDB=
GOWORK=
GOMODCACHE=/home/delaney/.gvm/pkgsets/go1.20.1/global/pkg/mod
GOSUMDB=sum.golang.org
GOMOD=/home/delaney/work/templtest/go.mod
GOPATH=/home/delaney/.gvm/pkgsets/go1.20.1/global
GOPROXY=https://proxy.golang.org,direct
GOCACHE=/home/delaney/.cache/go-build


[Info  - 4:28:32 PM] 2023/02/15 16:28:32 go/packages.Load #1
	snapshot=0
	directory=file:///home/delaney/work/templtest
	query=[builtin example/...]
	packages=2

[Info  - 4:28:32 PM] 2023/02/15 16:28:32 go/packages.Load #1: updating metadata for 134 packages

[Error - 4:30:49 PM] Request textDocument/definition failed.
  Message: no identifier found
  Code: 0 
```

**Comment by a-h** [comment]
No, I've not moved on. I won't be able to work on it this weekend though, so it will be next weekend before I pick it up.

I've been doing some work on a new parser that uses Go generics and is  therefore a lot simpler than my previous one, doesn't require so many functions and type switches etc.

I was planning to migrate the backend of templ to that to reduce the overall amount of code.

Then planned to pick up the LSP side again - because I have noticed some weird behaviour.

**Comment by a-h** [comment]
I have taken some time out to build an OpenAPI 3 generator for REST APIs because I need it for something at work https://github.com/a-h/rest

**Comment by delaneyj** [comment]
I noticed you where having issues parsing the original quicktemplate as well.  If I could make you a PEG parser that handed the right structure directly to you would that help?  I know a bit about the initial steps but not how to integrate with the language server.  I've used some of your JSONSchema work in the past and great to see you are still exploring the space, curious what an OpenAPI 3.1 would look like.  I have a project that I'm deciding on something like gomponents but really like quicktemplates.  I'll be available on gopher slack if you want to talk in further detail.  Have ideas on how to be faster than quicktemplate even.

**Comment by a-h** [comment]
I really dislike JSON Schema, I only wrote that JSON struct generator for a single project that I did 5 years ago, where the architect I was working with refused to read or write code, and wanted to an XML schema tool to design overly complex messages that were hard to implement and contained redundant/pointless data. I couldn't deal with the rate of changes, so I had to automate it. :)

I feel that project is languishing, and I should openly retire it, since I don't intend on using it myself in the future. 

But... I've been looking at various alternatives like Cue, Protobuf, Buf.build, Capnproto, AWS's Smithy tool etc. I need some way to document REST APIs from a code-first angle. With great regret, it seems that OpenAPI is the best way to deal with it at the moment.

Sounds like I'll have to get on this Gopher's Slack...

**Comment by delaneyj** [comment]
I sent you a direct message on the Gopher slack. It has your exact first and last name and looks like the timestamp for your local time is in the UK so if you're not on there that's pretty weird. But really whatever way to talk is most convenient for you. I agree JSON API is pretty rough. I'm actually redoing my stuff with htmx right now for the user interface and it's so much simpler. For RPC type stuff I'm a big fan of doing buf/connect or drpc with the auto generating documentation. In the protobuf space there's some decent tooling around generating from the introspection of the live server, plus the IDL tells you exactly the shape of the server calls and messages anyway unlike json where you have to be very explicit to get a decent response.  Anyway, what you've done with templ seems very valuable and hope it can be extended into other areas than just HTML. Look forward to talking to you soon

**Comment by a-h** [comment]
I've done some work towards making it easier to debug what's going on inside the LSP.

The latest commit https://github.com/a-h/templ/commit/d613ea88fe3be1770651eff86a94c0177dfdc740 can enable templ to start up a web server where you can view the contents of the LSP - i.e. what it thinks the Go and templ files are, and the mapping between them.

<img width="1920" alt="Screenshot 2023-02-19 at 20 37 38" src="https://user-images.githubusercontent.com/1029947/219973900-c153178d-d247-40a0-9d85-f17a34f39d05.png">

In Neovim, it's possible to configure the commands that the LSP uses, so it's really easy to add the extra `-http` flag.

```lua
local configs = require('lspconfig.configs')
configs.templ = {
  default_config = {
    cmd = { "templ", "lsp", "-http=localhost:7474", "-log=/Users/adrian/templ.log" },
    filetypes = { 'templ' },
    root_dir = nvim_lsp.util.root_pattern("go.mod", ".git"),
    settings = {},
  };
}
```

In VS Code, I'll need to add some sort of configuration property to be able to add the http setting in there, much like it's already possible to set the log parameter.

Hopefully, this combination of logs and visualisation will make it much easier to find out where the LSP is going wrong.

**Comment by a-h** [comment]
I have set up the new configuration value in templ-vscode, but haven't tested and deployed a new version yet.

See this commit: https://github.com/a-h/templ-vscode/commit/89c4ce5e8ba6ee298d00885c9356477293ac4718

**Comment by delaneyj** [comment]
Try cloning and running with the launch.json option.  Opens a new code instance but not sure what to do here.  In the new instance the extensions tab has templ-vscode but says reload required, but stays that way even after reload.

**Comment by a-h** [comment]
I've updated templ's LSP behaviour in: 

https://github.com/a-h/templ/commit/b49ef6fc9a4eae18a44de46417525a7b38646dd2
https://github.com/a-h/templ/commit/559ad84fc248ff4856416cb58fef4c534c317150
https://github.com/a-h/templ/commit/8f821bdc4e0216884d52db1927da1657fa77a9ea

If you have time to test out building the latest commit, that would be great. The problem isn't in the VS Code plugin, it's just where you're seeing it.

**Comment by delaneyj** [comment]
`
go install github.com/a-h/templ/cmd/templ@latest
templ version
v0.2.194
`
same test.templ

`[{
	"resource": "/home/delaney/work/rethink/test.templ",
	"owner": "_generated_diagnostic_collection_name_#0",
	"severity": 8,
	"message": "expected declaration, found 'package'",
	"source": "syntax",
	"startLineNumber": 530,
	"startColumn": 1,
	"endLineNumber": 530,
	"endColumn": 1
}]`

**Comment by a-h** [comment]
Ah, sorry, I wasn't clear. If you do a `go install` with `@latest`, Go modules will pull the latest git tag according to semantic versioning.

Since I hadn't pushed a tag, you got the previous version.

If you want to install a specific commit, you have to do `@commithash` instead, e.g. `@8f821bdc4e0216884d52db1927da1657fa77a9ea`.

I've pushed a tag now, so `@latest` will bring in the updated code.

**Comment by a-h** [comment]
Oh no, I've ran into a weirdness with Go install. What a rabbit hole I've fallen into.

It turns out that if you add a `replace` directive to a `go.mod` file, then `go install` no longer works. I'm not really sure why - I thought Go install cloned the repo, ran Go build and put the output in a binary location, but apparently, it does something else. 🤷🏻 

There's a massive discussion here - https://github.com/golang/go/issues/40276 but no guidance, as per https://github.com/golang/go/issues/40276#issuecomment-701898151

So I've asked the question https://groups.google.com/g/golang-nuts/c/tveOKkxNN1w but had no reply so far.

My current thinking is to either:

* Replace the installation instructions and stop using `go install` (probably going to do this anyway, I've lost trust).
* Hard fork the downstream library, since I don't want to wait for go.lsp.dev/protocol (https://github.com/go-language-server/protocol) to accept my PR. Then I can switch it back afterwards.

**Comment by delaneyj** [comment]
So with building and putting in /usr/local/bin finally no compile errors in .templ (you do have to `templ generate` at least once to get it to work.  But I'm still hitting issues as soon as I edit undo/redo a template.  Weird fragments of what looks like a partial buffer slice show up.

**Comment by a-h** [comment]
I've fixed up the installation procedure by hard forking the downstream library.

Thanks for testing that. I've tested undo/redo behaviour in Neovim on the latest version (0.2.208) and it works OK in Neovim, I'll get into VS Code this weekend and give it a blast.

**Comment by delaneyj** [comment]
bump

**Comment by a-h** [comment]
Hi, sorry for going quiet, but I haven't forgotten about this. I've got a new build of the `templ` lsp to go out.

There are 5 relevant commits that I think help to resolve the general issues with the LSP behaviour:

* https://github.com/a-h/templ/commit/5fae7ff4cc054d88e9c354c0ebc72398d1d2ff52 - fix bug in 3rd party library that results in inserting not overwriting text
* https://github.com/a-h/templ/commit/60f47999f9ee1d79fe46b81808ed2a8aa7c8681f - fix support for multiline go expressions
* https://github.com/a-h/templ/commit/a76a1145973f9fe3dfdbd5b3a7baeb1dc061fdc7 - fix the reported position of LSP diagnostics like imports, which were previously being inaccurately remapped to cover until the end of the file, not the end of the line
* https://github.com/a-h/templ/commit/b1973fd4b7d696387d683150b27c6ceac397d618 - fixed bug with extra newlines being added during some LSP operations
* https://github.com/a-h/templ/commit/120aaa285879b1e3188d37ec0e2d52ef577a24c4 - stop adding extra lines at the end of reformat operations

I just need to tag another release for these.

**Comment by a-h** [comment]
Following up again after our hangout conversation, I've had a chance to rewrite the templ document buffer.

I kept all the tests, added some more, and rewrote the implementation. By the end of it, the code was simpler, which is always a good sign.

* https://github.com/a-h/templ/compare/2fa1f0dfd919e0d40d5de129a6b6a0269ea9c14f...2fccbf31d7745d1b02322945449bb16ff1787014

With this, I could do undo/redo in VS Code without issues.

There's a new release of templ with the changes in https://github.com/a-h/templ/releases/tag/v0.2.233
